<?php

// Выход (успех)
return [
	// Система
	'empty' => 'Пусто',
	'yes' => 'Да',
	'no' => 'Нет',

	// Главное меню
	'menu_title' => 'Главное меню',
	'menu_description_guest' => "🔥 *Создайте ваш первый проект* и получите *ориентировочную стоимость* всего за 2 минуты",
	'menu_description_partner' => 'Благодарим за выбор нашей команды',
	'menu_cooperation' => '_Стараемся, чтобы сотрудничество с нами было максимально *комфортным* и *эффективным*_',
	'menu_update' => 'Последнее обновление',
	'menu_button_project_new' => 'Создать',
	'menu_button_projects' => 'Проекты',
	'menu_button_operator' => 'Связь с оператором',

	// Аккаунт
	'account_title' => 'Аккаунт',
	'account_authorized_system' => 'Доступ к системе',
	'account_authorized_settings' => 'Доступ к изменению настроек',
	'account_authorized_system_settings' => 'Системный доступ к системным настройкам',

	// Проект: создание
	'project_title' => 'Создание проекта',
	/* 'project_description' => "Расчитайте ориентировочное время разработки, затем выберите разработчиков и получите стоимость\n\nПосле расчётов можно будет отправить проект в заказ разработчикам и приложить ТЗ, либо краткое описание задачи\n\nМы погружаемся в проекты полностью, поэтому стараемся не распыляться - от степени нагрузки меняется коэффициент стоимости!", */
	'project_description' => "Установите параметры и получите ориентировочное время разработки\n\n_После расчётов можно отправить проект в заказ приложив ТЗ, либо описание задачи_",
	'project_warning_cost' => "Стоимость и сроки выполнения предоставлены для планирования и *не являются публичной офертой*",
	'project_team_warning' => "",
	'project_time' => 'Время',
	'project_time_hours' => 'ч',
	'project_time_hours_from' => 'от',
	'project_time_days' => 'дн',
	'project_cost' => 'Стоимость',
	'project_cost_prepayment' => 'Предоплата',
	'project_team_title' => 'Сбор команды',
	'project_team_description' => '_Вы можете *убрать* или *добавить* специалистов, создавая максимально удобное сотрудничество под вашу систему_',
	'project_team_warning_cost' => '_*Не влияет на время разработки*_',
	'project_team_button_programmers' => 'Программисты: %d%s',
	'project_team_button_designers' => 'Дизайнеры: %d%s',
	'project_team_button_boosters' => 'Бустеры: %d%s',
	'project_team_programmers_title' => 'Количество программистов',
	'project_team_programmers_description' => 'Никаких копий по шаблонам и конструкторов, только *чистый код с нуля* и наши *уникальные технологии* с *многолетней кодовой базой*',
	'project_team_programmers_request' => '_Отправьте предложение по *количеству программистов*_',
	'project_team_programmers_error_amount' => 'Мы можем предоставить до %d программистов',
	'project_team_designers_title' => 'Количество дизайнеров',
	'project_team_designers_description' => 'У каждого дизайнера своё *уникальное видение*, поэтому мы стараемся находить максимально подходящих под проект, но зачастую мы привлекаем сторонних дизайнеров\. Если у заказчика имеются свои проверенные дизайнеры, то мы готовы с ними сотрудничать',
	'project_team_designers_request' => '_Отправьте предложение по *количеству дизайнеров*_',
	'project_team_designers_error_amount' => 'Мы можем предоставить до %d дизайнеров',
	'project_team_boosters_title' => 'Количество бустеров',
	'project_team_boosters_description' => '*Бустер* \- обобщение для специалистов которые занимаются *маркетингом*, *рекламными кабинетами*, дошлифовкой интерфейса, *user\-experience*, А\/Б тестированием, сбором фокус\-группы, развитием сообщества и в целом *SMM*',
	'project_team_boosters_request' => '_Отправьте предложение по *количеству бустеров*_',
	'project_team_boosters_error_amount' => 'Мы можем предоставить до %d бустеров',
	'project_team_error_not_a_number' => 'Значение должно быть числом',
	'project_cost_title' => 'Стоимость разработки',
	'project_cost_description' => '*`%d%s`* \- средняя стоимость с учётом *компетенции*, совокупного опыта, *уникальных* разработок\. Цена уже включает\: *наши сервера*, документирование кода, *передачу кода*, ведение репозитория, *техподдержку* и репутационные гарантии',
	'project_cost_request' => '_Отправьте предложение по *оплате за 1 час* разработки_',
	'project_cost_warning' => '_Если цена окажется *недостаточной*, мы выставим *справедливое* и *конкурентное* встречное предложение_',
	'project_cost_error_distance' => 'Длина сообщения должна быть от %d и до %d символов',
	'project_cost_error_not_a_number' => 'Значение должно быть числом',
	'project_button_back' => 'Назад',
	'project_button_cost_per_hour' => 'Час',
	'project_button_request' => 'Заказать',

	'project_architectures_title' => 'Выбор архитектуры проекта',
	'project_architectures_description' => 'Каждая архитектура имеет уникальные параметры и коэффициенты \- это основа дальнейших расчётов\!',
	'project_button_architecture' => 'Архитектура',
	'project_button_architecture_selected' => 'Архитектура',

	'project_purposes_title' => 'Выбор назначения',
	'project_purposes_description' => 'Вектор разработки, основание проекта',
	'project_button_purpose' => 'Назначение',
	'project_button_purpose_selected' => 'Назнач.',

	'project_integrations_title' => 'Выбор интеграций',
	'project_integrations_description' => "Синхронизация заказов, товаров, публикаций и прочего в реальном времени, скачивание, загрузка, админ\-панель, рассылка сообщений, подключение аккаунтов\.\.\.\n\n_Отправка запросов в *API*, генерация и перехват *HTTP\-сообщений*, *эмуляция действий пользователя*_",
	'project_button_integrations' => 'Интеграции',
	'project_button_integrations_selected' => 'Интеграции',
	'project_button_team' => 'Команда: %d%s',
	'project_peoples' => '',
	'project_cancelled' => 'Создание проекта отменено',
	'project_deal_requested' => 'Проект создан и отправлен оператору',
	'project_deal_title' => 'Заказ #%d',
	'project_deal_architecture' => 'Архитектура',
	'project_deal_purpose' => 'Назначение',
	'project_deal_time' => 'Время',
	'project_deal_time_hours' => 'ч',
	'project_deal_time_hours_from' => 'от',
	'project_deal_time_days' => 'дн',
	'project_deal_cost' => 'Стоимость',
	'project_deal_team' => 'Команда',
	'project_deal_empty' => 'Пусто',
	'project_deal_button_accept' => 'Принять',
	'project_deal_button_refuse' => 'Отказать',
	'project_deal_button_edit' => 'Редактировать',
	'project_deal_button_chat' => 'Чат с заказчиком',
	'project_accepted_deal_not_found' => 'Не удалось найти заявку',
	'project_accepted_project_not_found' => 'Не удалось найти проект',
	'project_accepted_already_confirmed' => 'Сделка уже проведена',
	'project_accepted_title' => 'Заказ подтверждён\!',
	'project_accepted_description' => 'Мы изучили предложение и *согласились* на условия',
	'project_accepted_prepayment' => 'Предоплата',
	'project_accepted_documents' => '_При желании оформить договор о неразглашении и передаче прав, *обратитесь к оператору*_',
	'project_accepted_confirmed' => 'Подтверждено',
	'project_accepted_button_prepayment' => 'Оплатить через СБП',

	// Проект: типы
	'project_architecture_chat_robot' => 'Чат-робот',
	'project_architecture_parser' => 'Парсер',
	'project_architecture_calculator' => 'Калькулятор',
	'project_architecture_crm' => 'CRM',
	'project_architecture_site' => 'Сайт',
	'project_architecture_program' => 'Программа',
	'project_architecture_complex' => 'Нестандартная',

	// Проект: назначение
	'project_purpose_funnel' => 'Воронка',
	'project_purpose_contact' => 'Контакты',
	'project_purpose_neural_network' => 'Нейросеть',
	'project_purpose_gallery' => 'Галерея',
	'project_purpose_crm' => 'CRM',
	'project_purpose_landing' => 'Лендинг',
	'project_purpose_marketplace' => 'Маркетплейс',
	'project_purpose_charity' => 'Благотворительность',
	'project_purpose_search' => 'Поиск',
	'project_purpose_calcul+ate' => 'Расчёт',
	'project_purpose_tools' => 'Инструменты',
	'project_purpose_workers' => 'Рабочие',
	'project_purpose_objects' => 'Предметы',
	'project_purpose_events' => 'События',
	'project_purpose_special' => 'Особенное',

	// Проект: интеграции
	'project_integration_one_c' => '1C',
	'project_integration_bitrix24' => 'Битрикс 24',
	'project_integration_moy_sklad' => 'Мой Склад',
	'project_integration_telegram' => 'Телеграм',
	'project_integration_mail' => 'Почта',
	'project_integration_excel' => 'Excel',
	/* 'project_integration_' => '', */

	// Настройки: язык
	'settings_language_title' => 'Выбери язык',
	'settings_language_description' => 'Выбранный язык будет использоваться для генерации системного отображения',
	'settings_language_update_success' => 'Язык заменён',
	'settings_language_update_fail' => 'Не удалось заменить язык',
	'settings_language_button_add' => 'Добавить язык',

	// Авторизация
	'authorization_system' => 'Система',
	'authorization_settings' => 'Настройки',
	'not_authorized_system' => 'Запрещён доступ к системе',
	'not_authorized_settings' => 'Запрещён доступ к настройкам',
	'not_authorized_system_settings' => 'Запрещён системный доступ к настройкам',
	'not_authorized_system_deals' => 'Запрещён системный доступ к сделкам',
	'not_authorized_system_projects' => 'Запрещён системный доступ к проектам ',
	'not_authorized_system_invoices' => 'Запрещён системный доступ к счетам',

	// Сообщения
	'message_initialization_fail' => 'Не удалось инициализировать сообщение Телеграм',
	'message_text_initialization_fail' => 'Не удалось инициализировать текст сообщения Телеграм',

	'error_title' => 'Перегрузка\!',
	'error_description' => 'Чат\-робот обрабатывает *длинную очередь* запросов',
	'error_repeat' => 'Если не заработает *через 30 минут*, пишите оператору',
	'error_account' => 'Аккаунт',
	'error_button_chat_user' => 'Чат с пользователем',
	'error_button_chat_operator' => 'Чат с оператором',

	// Прочее
	'why_so_shroomious' => 'почему такой грибъёзный'
];
